# See https://redocly.com/docs/cli/configuration/ for more information.
apis:
  sample@v1: 
    root: openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: error
features.openapi:
  showConsole: true
  htmlTemplate: ./docs/index.html
  corsProxyUrl: https://cors.redoc.ly/
  theme:
    colors:
      accent:
        main: "#000000"
  # generateCodeSamples:
  #   languages:  # Array of language config objects; indicates in which languages to generate code samples.
  #     - lang: curl
  #     - lang: Node.js
  #     - lang: JavaScript
  #     - lang: PHP
  #     - lang: Python

