# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  main: openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  showConsole: true
  corsProxyUrl: https://cors.redoc.ly/  
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"